import type { AttendanceStatus, SessionAttendanceResult } from "@classroom-os/types";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { AppButton, AppHeader, Card, ConfirmationModal, ErrorState, LoadingSkeleton, SafeScreen, StatusBadge } from "@/components/ui/primitives";
import { colors, radius, spacing, touchTarget } from "@/constants/tokens";
import { useAuth } from "@/features/auth/auth-context";
import { useAuthenticatedQuery } from "@/hooks/use-authenticated-query";
import { apiRequest } from "@/lib/api-client";
import { thaiErrorMessage } from "@/lib/api-error";

import { buildAttendanceBatch } from "./build-attendance-batch";

const statusOptions: { value: AttendanceStatus; label: string }[] = [{ value: "present", label: "มา" }, { value: "late", label: "สาย" }, { value: "absent", label: "ขาด" }, { value: "leave", label: "ลา" }];
const memoryDrafts = new Map<string, Record<string, AttendanceStatus>>();
export function AttendanceScreen({ sessionId, classroomId }: { sessionId: string; classroomId: string }) {
  const { token } = useAuth(); const queryClient = useQueryClient(); const [search, setSearch] = useState(""); const [discardOpen, setDiscardOpen] = useState(false); const [saved, setSaved] = useState(false);
  const roster = useAuthenticatedQuery<SessionAttendanceResult>(["attendance", sessionId], `/api/sessions/${sessionId}/attendance?classroomId=${encodeURIComponent(classroomId)}`);
  const [draft, setDraft] = useState<Record<string, AttendanceStatus>>(() => memoryDrafts.get(sessionId) ?? {});
  const setStatus = (studentId: string, status: AttendanceStatus) => setDraft((current) => { const next = { ...current, [studentId]: status }; memoryDrafts.set(sessionId, next); setSaved(false); return next; });
  const changed = useMemo(() => roster.data?.students.filter((student) => draft[student.studentId] && draft[student.studentId] !== student.status).length ?? 0, [draft, roster.data]);
  const filtered = roster.data?.students.filter((student) => `${student.studentNumber} ${student.firstName} ${student.lastName}`.toLocaleLowerCase("th").includes(search.trim().toLocaleLowerCase("th"))) ?? [];
  const save = useMutation({ mutationFn: () => apiRequest<SessionAttendanceResult>(`/api/sessions/${sessionId}/attendance`, { method: "PUT", token, body: { classroomId, records: buildAttendanceBatch(roster.data!.students, draft) } }), onSuccess: async () => { memoryDrafts.delete(sessionId); setDraft({}); setSaved(true); await queryClient.invalidateQueries({ queryKey: ["attendance", sessionId] }); await queryClient.invalidateQueries({ queryKey: ["session", sessionId] }); } });
  if (roster.isLoading) return <LoadingSkeleton />;
  if (roster.error || !roster.data) return <SafeScreen><ErrorState message={thaiErrorMessage(roster.error)} onRetry={() => void roster.refetch()} /></SafeScreen>;
  const readOnly = roster.data.status !== "live";
  return <SafeScreen><AppHeader title="เช็กชื่อ" subtitle={`บันทึกแล้ว ${roster.data.recordedCount}/${roster.data.enrolledCount} คน`} />{readOnly ? <StatusBadge label="คาบนี้อ่านอย่างเดียว" tone="warning" /> : null}<TextInput accessibilityLabel="ค้นหานักเรียน" placeholder="ค้นหาชื่อหรือรหัสนักเรียน" value={search} onChangeText={setSearch} style={styles.search} />{!readOnly ? <AppButton label="มาครบทุกคน" tone="secondary" onPress={() => { const next = Object.fromEntries(roster.data!.students.map((student) => [student.studentId, "present"])) as Record<string, AttendanceStatus>; memoryDrafts.set(sessionId, next); setDraft(next); setSaved(false); }} /> : null}{filtered.map((student) => { const current = draft[student.studentId] ?? student.status; return <Card key={student.studentId}><View><Text style={styles.name}>{student.firstName} {student.lastName}</Text><Text style={styles.code}>{student.studentNumber}</Text></View><View accessibilityRole="radiogroup" style={styles.controls}>{statusOptions.map((option) => <Pressable key={option.value} accessibilityRole="radio" accessibilityLabel={`${student.firstName} ${option.label}`} accessibilityState={{ checked: current === option.value, disabled: readOnly }} disabled={readOnly} onPress={() => setStatus(student.studentId, option.value)} style={({ pressed }) => [styles.status, current === option.value && styles.selected, pressed && styles.pressed]}><Text style={[styles.statusText, current === option.value && styles.selectedText]}>{option.label}</Text></Pressable>)}</View>{student.corrections.length ? <Text style={styles.correction}>แก้ไขย้อนหลัง {student.corrections.length} ครั้ง</Text> : null}</Card>; })}{!readOnly ? <View style={styles.save}><Text style={styles.pending}>รายการที่เปลี่ยน {changed} คน</Text><AppButton label={save.isPending ? "กำลังบันทึก…" : "บันทึกการเช็กชื่อ"} disabled={save.isPending || changed === 0} onPress={() => save.mutate()} />{changed ? <AppButton label="ยกเลิกการเปลี่ยนแปลง" tone="secondary" onPress={() => setDiscardOpen(true)} /> : null}</View> : null}{saved ? <Text accessibilityRole="alert" style={styles.success}>บันทึกเรียบร้อยแล้ว</Text> : null}{save.error ? <ErrorState message={`${thaiErrorMessage(save.error)} หากข้อมูลเปลี่ยนจากอุปกรณ์อื่น กรุณาโหลดใหม่`} onRetry={() => save.mutate()} /> : null}<ConfirmationModal visible={discardOpen} title="ทิ้งการเปลี่ยนแปลง?" description={`มี ${changed} รายการที่ยังไม่บันทึก`} confirmLabel="ทิ้งการเปลี่ยนแปลง" destructive onConfirm={() => { memoryDrafts.delete(sessionId); setDraft({}); setDiscardOpen(false); }} onCancel={() => setDiscardOpen(false)} /></SafeScreen>;
}
const styles = StyleSheet.create({ search: { minHeight: touchTarget, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.surface, paddingHorizontal: spacing.md, fontSize: 16 }, name: { color: colors.text, fontSize: 17, fontWeight: "700" }, code: { color: colors.muted, marginTop: 3 }, controls: { flexDirection: "row", gap: spacing.sm }, status: { flex: 1, minHeight: touchTarget, borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm, justifyContent: "center", alignItems: "center" }, selected: { backgroundColor: colors.primary, borderColor: colors.primary }, pressed: { opacity: 0.7 }, statusText: { color: colors.text, fontWeight: "700" }, selectedText: { color: colors.surface }, correction: { color: colors.muted, fontSize: 13 }, save: { gap: spacing.md, backgroundColor: colors.surface, borderTopWidth: 1, borderColor: colors.border, paddingTop: spacing.lg }, pending: { color: colors.text, fontWeight: "700" }, success: { color: colors.success, fontWeight: "700", textAlign: "center" } });
