"use client";

import type { AcademicYearResult, TermResult } from "@classroom-os/types";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useId, useState } from "react";

import { EmptyCollectionState } from "@/components/admin/admin-state";
import { StatusBadge } from "@/components/status-badge";
import { requestApi, thaiApiError } from "@/lib/client-api";

const inputStyles = "min-h-11 w-full rounded-xl border border-[#E5E7EB] px-4 py-3 text-sm outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-600/20";

export function TermManager({ years, terms }: { years: AcademicYearResult[]; terms: TermResult[] }) {
  const router = useRouter(); const formId = useId(); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setPending(true); setError(null); try { await requestApi<TermResult>("/api/terms", { body: { academicYearId: data.get("academicYearId"), name: data.get("name"), startsOn: data.get("startsOn"), endsOn: data.get("endsOn"), isCurrent: data.get("isCurrent") === "on" } }); form.reset(); router.refresh(); } catch (submitError) { setError(thaiApiError(submitError)); } finally { setPending(false); } }
  async function markCurrent(id: string) { setPending(true); setError(null); try { await requestApi(`/api/terms/${id}`, { method: "PATCH", body: { isCurrent: true } }); router.refresh(); } catch (submitError) { setError(thaiApiError(submitError)); } finally { setPending(false); } }
  return <div className="mt-8 space-y-6"><form onSubmit={create} className="rounded-2xl border border-[#E5E7EB] bg-white p-5 shadow-sm" aria-labelledby={`${formId}-heading`}><h2 id={`${formId}-heading`} className="text-lg font-bold">เพิ่มภาคเรียน</h2>{years.length === 0 ? <p className="mt-4 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-900">ต้องเพิ่มปีการศึกษาก่อน <Link href="/academic-years" className="font-semibold underline">ไปที่ปีการศึกษา</Link></p> : <><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div><label htmlFor={`${formId}-year`} className="mb-2 block text-sm font-semibold">ปีการศึกษา</label><select id={`${formId}-year`} name="academicYearId" required defaultValue={years.find((year) => year.isCurrent)?.id ?? years[0]?.id} className={inputStyles}>{years.map((year) => <option key={year.id} value={year.id}>{year.name}</option>)}</select></div><div><label htmlFor={`${formId}-name`} className="mb-2 block text-sm font-semibold">ชื่อภาคเรียน</label><input id={`${formId}-name`} name="name" required placeholder="ภาคเรียนที่ 1" className={inputStyles} /></div><div><label htmlFor={`${formId}-start`} className="mb-2 block text-sm font-semibold">วันเริ่มต้น</label><input id={`${formId}-start`} name="startsOn" type="date" required className={inputStyles} /></div><div><label htmlFor={`${formId}-end`} className="mb-2 block text-sm font-semibold">วันสิ้นสุด</label><input id={`${formId}-end`} name="endsOn" type="date" required className={inputStyles} /></div></div><label className="mt-4 flex w-fit items-center gap-2 text-sm"><input type="checkbox" name="isCurrent" className="size-4 accent-blue-600" /> กำหนดเป็นภาคเรียนปัจจุบัน</label></>}{error ? <p className="mt-4 text-sm text-red-700" role="alert">{error}</p> : null}<div className="mt-5 flex justify-end"><button type="submit" disabled={pending || years.length === 0} className="min-h-11 rounded-xl bg-blue-600 px-5 py-2 text-sm font-semibold text-white focus-visible:ring-2 focus-visible:ring-blue-600 focus-visible:ring-offset-2 disabled:opacity-60">{pending ? "กำลังบันทึก…" : "เพิ่มภาคเรียน"}</button></div></form>
  <section className="overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white shadow-sm" aria-labelledby="term-list-heading"><div className="flex items-center justify-between border-b px-5 py-4"><h2 id="term-list-heading" className="font-bold">ภาคเรียนทั้งหมด</h2><Link href="/academic-years" className="rounded-md text-sm font-semibold text-blue-700 focus-visible:ring-2 focus-visible:ring-blue-600">จัดการปีการศึกษา</Link></div>{terms.length === 0 ? <EmptyCollectionState title="ยังไม่มีภาคเรียน" description="เพิ่มภาคเรียนเพื่อกำหนดขอบเขตงานสอนและตารางสอน" /> : <ul className="divide-y divide-slate-100">{terms.map((term) => <li key={term.id} className="flex flex-col gap-4 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-3"><p className="font-semibold">{term.name} · {term.academicYearName}</p>{term.isCurrent ? <StatusBadge variant="info">ปัจจุบัน</StatusBadge> : null}</div><p className="mt-1 text-sm text-[#6B7280]">{term.startsOn} – {term.endsOn}</p></div>{!term.isCurrent ? <button type="button" disabled={pending} onClick={() => void markCurrent(term.id)} className="min-h-11 rounded-xl border border-blue-600 px-4 py-2 text-sm font-semibold text-blue-700 focus-visible:ring-2 focus-visible:ring-blue-600 disabled:opacity-60">กำหนดเป็นปัจจุบัน</button> : null}</li>)}</ul>}</section></div>;
}
